### ISSUE TITLE
Terminology across all Web Payments documents should be aligned

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#135]
Migrated from https://github.com/w3c/browser-payment-api/issues/43 by @msporny 

Migrating from https://github.com/w3c/webpayments/issues/23:

The specs should import the Web Payments IG glossary. An example of how to do this is in the Web Payments CG's Browser API spec:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/index.html#L170-L177

You will also need to include a script here:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/index.html#L13

which can be found here:

https://github.com/WICG/web-payments-browser-api/blob/5034393370c54226eb13fbdacde2462ba5e11713/utils.js

Spec refs:
http://wicg.github.io/paymentrequest/specs/architecture.html#glossary
http://wicg.github.io/web-payments-browser-api/#terminology

**Comment by adrianhopebailie** [comment]
It would be useful if someone familiar with this linked glossary system worked with the existing spec editors to add it to our specs (possibly by submitting a PR)

**Comment by ianbjacobs** [comment]
I support term harmonization. I believe the IG should look at the WG's terms and see if harmonization is appropriate by potentially making changes to the IG glossary. 

I do not support including terms that are not used in the WG's document. In general, mechnically including the same document seems very low priority to me.

Ian

**Comment by adrianhopebailie** [comment]
@ianbjacobs

> I do not support including terms that are not used in the WG's document.

+1 - My understanding of how this works is that through a script include you are able to specify terms from the remote glossary that are then included in the local definitions (i.e. not all terms are pulled in)

Hence my suggestion that someone submit a PR so we can get a view of what this proposal would actually look like if adopted.

**Comment by msporny** [comment]
@halindrome and @msporny know how to do this. It's not difficult, you just need 3 lines of code, example here:

https://github.com/w3c/webpayments-http-api/blob/gh-pages/index.html#L166

I'd volunteer to do it, but I'd probably just pull all the terminology into the IG document and work it from there. I don't know if this would be ok w/ the current set of editors, so they should probably do it since they may have concerns about their vocabulary terms ending up in the IG glossary or vice versa.

**Comment by msporny** [comment]
@ianbjacobs wrote:

> I do not support including terms that are not used in the WG's document.

Terms that are not used in the document don't show up in the terminology section in the document.

Here's an example of pulling the IG glossary document in:

http://w3c.github.io/webpayments-http-api/#terminology

**Comment by tommythorsen** [comment]
@msporny 

> > I do not support including terms that are not used in the WG's document.
> 
> Terms that are not used in the document don't show up in the terminology section in the document.
> 
> Here's an example of pulling the IG glossary document in:
> 
> http://w3c.github.io/webpayments-http-api/#terminology

That terminology section does seem to contain terms that are not used anywhere in the document though. Try searching for "three corner model" or "payment orchestrator" for instance.

**Comment by msporny** [comment]
@tommythorsen wrote:

> Try searching for "three corner model" or "payment orchestrator" for instance.

Hmm, those terms don't show up in my version. Look at the top right of the page, you should have 1 orange warning, no red errors.

You need to force reload the page due to jumly HTTPS CDN issues. Are you using HTTPS to access the page? If so, don't. Use HTTP. I'm going to rip out the jumly stuff this week.

You might also have a very old/cached version of respec.js or you have a cached version of the glossary.

Try force refreshing this: https://w3c.github.io/webpayments-ig/latest/common/terms.html
or force-refreshing this: https://www.w3.org/Tools/respec/respec-w3c-common

Then reload the page.

The issue may be a result of W3C and github.io having very aggressive caching policies (which are okay, most of the time)... but not for client-side dynamically generated content.

In any case, one of the two approaches above should work for you. The culprit is probably Jumly (client-side diagram software), which will be removed later this week. I've seen the caching stuff be an issue as well.

**Comment by tommythorsen** [comment]
@msporny 

> Try force refreshing this: https://w3c.github.io/webpayments-ig/latest/common/terms.html
> or force-refreshing this: https://www.w3.org/Tools/respec/respec-w3c-common
> 
> Then reload the page.

Aha, one of those did the trick. It looks correct now. In that case, I can probably do the same for the payment apps document.

**Comment by tommythorsen** [comment]
@adrianhopebailie 
The payment apps document depends on a few definitions from the [architecture](https://w3c.github.io/webpayments/proposals/architecture/#definitions) document. Would you be ok with me stealing those definitions and adding them to the IG glossary document?

**Comment by adrianhopebailie** [comment]
@tommythorsen not at all. Put them in but know that we may still want to refine them.

**Comment by tommythorsen** [comment]
I've created a PR in webpayments-ig: https://github.com/w3c/webpayments-ig/pull/39

**Comment by tommythorsen** [comment]
@adrianhopebailie, @ianbjacobs 

It's been a couple of weeks now without a response from anyone in the IG about https://github.com/w3c/webpayments-ig/pull/41. Maybe we would be better off pulling their terminology document into this repo and managing it ourselves?

**Comment by dezell** [comment]
Hi @tommythorsen  :  Apologies, but I didn't see any specific query about this topic, or anything the IG should specifically be doing.  With apologies, can you please point me to the request?

FWIW the WG/IG agreed that the IG should manage the overall terminology for the WP Activity as far as feasible.

**Comment by tommythorsen** [comment]
@dezell: The PR is here: https://github.com/w3c/webpayments-ig/pull/41

**Comment by dezell** [comment]
So, @tommythorsen, I think that gives the following instructions to the IG.  Please stand by for when.
• Add: payment app
A payment app is a component able to process a <a>payment request</a> and return a <a>payment response</a>.

• Add: payment method specification
A payment method specification defines what <a>payment method data</a>is required in <a>payment requests</a> and <a>payment responses</a> for a particular <a>payment method</a>. It also lists the <a>payment method</a> identifiers that are defined for that <a>payment method</a>.

• Add: payment request
A request from a <a>payee</a> to be paid. It contains the details of what to pay and how the payment can be made. How the payment can be made is specified as a list of <a>payment method identifiers</a>. The payment request MUST contain all of the <a>payment method data</a> required for each <a>payment method</a> identified in it's set of supported payment methods.

• Add: payment response
A response to a <a>payment request</a> (normally the result of processing by a <a>payment app</a>). The content of a payment response will be dependant on how the <a>payment</a> is being processed.

• Add: payment method identifier
A string that uniquely identifies a <a>payment method</a> that a user can use to complete a transaction.

• Change: payment method specification
A payment method specification defines what <a>payment method data</a> is required in <a>payment requests</a> and <a>payment responses</a> for a particular <a>payment method</a>. It also lists the <a>payment method identifiers</a> that are defined for that <a>payment method</a>.

• Add: browser-based payment app
A <a>payment app</a> that runs in a <a>browser</a>.

• Add: displayed payment app
A <a title="matching payment app">matching</a> or <a>recommended payment app</a> presented by the <a>browser</a> for user selection.

• Add: enabled payment app
A <a>registered payment app</a> with at least one <a>enabled payment method</a>.

• Add: enabled payment method
For a given <a>payment app</a>, an enabled <a>payment method</a> is a <a>payment method</a> the user has configured the <a>payment app</a> to support.

• Add: headless payment app
A <a>payment app</a> that, per user configuration, the <a>user agent</a> does not display as matching and does not invoke for <a>payment</a>. A <a>payment app</a> may be ignored for some <a>transactions</a> and not ignored for others. For instance, if a <a>browser</a>allows a user to configure a default <a>payment app</a> for a particular Web site, other <a>payment apps</a> are considered ignored for that site.

• Add: ignored payment app
A <a>payment app</a> that, per user configuration, the <a>user agent</a> does not display as matching and does not invoke for <a>payment</a>. A <a>payment app</a> may be ignored for some <a>transactions</a> and not ignored for others. For instance, if a <a>browser</a> allows a user to configure a default <a>payment app</a> for a particular Web site, other <a>payment apps</a> are considered ignored for that site.

• Add: invoked payment app
A <a>selected payment app</a> that the <a>browser</a> has invoked by passing it a <a>payment request</a>.

• Add: matching payment app
An <a>enabled payment app</a> that:

<ul>
<li>has at least one <a>enabled payment method</a> that the
<a>payee</a> accepts.</li>
<li>is not an <a>ignored payment app</a>.</li>
</ul>

• Add: native payment app
A <a>payment app</a> built with the operating system default technology stack that uses non-Web technologies.

• Add: payment app input
Data provided to the <a>invoked payment app</a> by the <a>browser</a>.  This data is likely to be a subset of the <a>payment request API input</a> (e.g., <a>payment method</a>, <a title="payment method data">payment method specific data</a>, and <a>transaction</a> specific data).

• Add: payment app response
Data provided by the <a>invoked payment app</a> to the <a>browser</a>.

• Add: payment request API
The javascript API specified in the <a href="https://w3c.github.io/browser-payment-api/specs/paymentrequest.html"> Payment Request API</a> specification. This API can be used by <a>merchants</a> to trigger a payment flow in the <a>user agent</a> or by <a>payment apps</a> to register or update their information in the <a>user agent</a>.

• Add: payment request API input
Data provided by the <a>payee</a>'s Web application to the <a>browser</a> via the <a>payment request API</a>.

• Add: payment request API response
Data provided to the <a>payee</a>'s Web application by the <a>browser</a> after completion of the <a>payment request API</a>.

• Add: recommended payment app
An <a>unregistered payment app</a> recommended by the <a>payee</a> or <a>browser</a>.

• Add: registered payment app
A <a>payment app</a> that the user has successfully registered with the <a>browser</a>.

• Add: selected payment app
A <a>displayed payment app</a> selected by the user to process a <a>payment request</a> for a given <a>transaction</a>.

• Add: supported payment method
For a given <a>payment app</a>, a supported <a>payment method</a> is a <a>payment method</a> the user can configure the <a>payment app</a> to support.

• Add: unregistered payment app
A <a>payment app</a> that is unknown to the <a>browser</a>, either because it has never been registered, or it has been <a title="unregistered payment app">unregistered</a>.

• Add: unsupported payment method
For a given <a>payment app</a>, an unsupported <a>payment method</a> is a <a>payment method</a> the user cannot configure the <a>payment app</a> to support.

• Add: user agent
A piece of software that acts on behalf of the user.

• Add: web browser
A <a>user agent</a> that allows the user to render and view HTML documents, and navigate the World Wide Web.

• Add: web-based payment app
A <a>payment app</a> built using Open Web Platform technology. This includes both <a>browser-based payment apps</a>i and <a>headless payment apps</a>.

**Comment by ianbjacobs** [comment]
Closing as the specs have evolved and much work has gone into internal consistency.
