### ISSUE TITLE
How are payment apps registered?

### ISSUE THREAD

**Issue by msporny** [w3c/webpayments#14]
There are a variety of approaches that can be used to register payment instruments:
- Browser API call
- Installed by OS Platform (Android Pay, Apple Pay)
- Software installation (Chase Visa Card App)

Which one of these options are we going to support in Phase I?

**Comment by msporny** [comment]
If we had to pick one, I'd pick registration via a Browser API call and making the registration object a data-only object that can be acted on by various Browser APIs and HTTP APIs.

**Comment by mattsaxon** [comment]
+1

**Comment by rsolomakhin** [comment]
Perhaps we can reuse the Web App Manifest logic from http://www.w3.org/TR/appmanifest/#installability-signals :

"This specification does not provide developers with an explicit API to 'install' a web application. Instead, a manifest can serve as an installability signal to a user agent that a web application can be installed."

**Comment by msporny** [comment]
@rsolomakhin The most concerning part of the installability section of the Web App manifest spec is the following:

> How a user agent makes use of these installability signals to determine if a web application can be installed is left to implementers.

In general, I'm a bit wary of the whole 'payment instrument as app manifest' approach because there is no trigger that a site can call to be sure that the payment instrument was installed. I'm also not sure what the polyfill story for manifest-based payment instruments are.

So, a few questions:
1. What are the upsides and downsides to a manifest-based approach?
2. How does a site that issues payment instruments know if a payment instrument has been installed (or is available)?
3. How would a manifest-based approach be polyfilled?

**Comment by dlongley** [comment]
I have a preference for considering [The Rule of Least Power](http://www.w3.org/2001/tag/doc/leastPower.html) here. What that means to me is that payment instruments should either be data-only or their self-description (in manifest form for example) must provide enough information for user agents to retrieve and automatically install the software necessary to make use of them from the Web.

**Comment by adrianhopebailie** [comment]
> their self-description (in manifest form for example) must provide enough information for user agents to retrieve and automatically install the software necessary to make use of them from the Web.

+1 - in terms of what we standardize.

We should specify a mechanism for payment apps to be registered via the browser API as a minimum and then expect platform vendors to offer other ways to achieve the same outcome as they see fit (installed as an app on mobile, as a browser extension on desktop etc).

This may be as simple as:

``` javascript
navigator.payments.registerPaymentApp({
    "id" : "https://xyzbank.com/app/"
    "label" : "XYZ Bank",
    "icon"  : "https://xyzbank.com/icons/app.png",
    "supportedPaymentMethods" : ["https://visa.com/debit/v2", "https://bitcoin.org"],
    "endpoint" : "https://xyzbank.com/app/"
});
```

I'd expect the payment mediator to also record what origin this app was installed from and block installation if the endpoint is not at the same origin. Further, I'd expect the payment mediator to offer a way for the app to update the set of supported payment methods over time.

An additional feature I'd like to see is an API like the following that allows app publishers to probe if their app is installed:

``` javascript
navigator.payments.isPaymentAppInstalled({"https://xyzbank.com/app/"});
```

This API would only ever return true if the call is made from the same origin as the that which registered the app.

If the app was registered through an alternative mechanism then it should be able to specify it's origin. (I believe app stores have ways of doing this on mobile platforms. i.e. tying apps to an origin.)

Manifests are one way to facilitate this but they shouldn't be the only one as this seems to imply a single origin can only ever publish a single payment app.

I would also prefer the registration of a payment app to be an explicit request from the publisher via the API than something a user may stumble into because they visited the site and it's manifest specifies it has a payment app.

**Comment by webpayments** [comment]
Why do you feel that the endpoint is required to be the same as the
origin?  I could imagine a payment app development house providing lots of
different payment apps for mom and pop (e.g., smaller) retailers.
Payment-Apps-R-Us would be the origin of the app and might even act as an
aggregator or something, but the endpoint is
www.bobs-groceries-and-gas.com/app/

On Wed, Dec 9, 2015 at 4:56 AM, Adrian Hope-Bailie <notifications@github.com

> wrote:
> 
> their self-description (in manifest form for example) must provide enough
> information for user agents to retrieve and automatically install the
> software necessary to make use of them from the Web.
> 
> +1 - in terms of what we standardize.
> 
> We should specify a mechanism for payment apps to be registered via the
> browser API as a minimum and then expect platform vendors to offer other
> ways to achieve the same outcome as they see fit (installed as an app on
> mobile, as a browser extension on desktop etc).
> 
> This may be as simple as:
> 
> navigator.payments.registerPaymentApp({
>     "id" : "https://xyzbank.com/app/"
>     "label" : "XYZ Bank",
>     "icon"  : "https://xyzbank.com/icons/app.png",
>     "supportedPaymentMethods" : ["https://visa.com/debit/v2", "https://bitcoin.org"],
>     "endpoint" : "https://xyzbank.com/app/"
> });
> 
> I'd expect the payment mediator to also record what origin this app was
> installed from and block installation if the endpoint is not at the same
> origin. Further, I'd expect the payment mediator to offer a way for the app
> to update the set of supported payment methods over time.
> 
> An additional feature I'd like to see is an API like the following that
> allows app publishers to probe if their app is installed:
> 
> navigator.payments.isPaymentAppInstalled({"https://xyzbank.com/app/"});
> 
> This API would only ever return true if the call is made from the same
> origin as the that which registered the app.
> 
> If the app was registered through an alternative mechanism then it should
> be able to specify it's origin. (I believe app stores have ways of doing
> this on mobile platforms. i.e. tying apps to an origin.)
> 
> Manifests are one way to facilitate this but they shouldn't be the only
> one as this seems to imply a single origin can only ever publish a single
> payment app.
> 
> I would also prefer the registration of a payment app to be an explicit
> request from the publisher via the API than something a user may stumble
> into because they visited the site and it's manifest specifies it has a
> payment app.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/webpayments/issues/14#issuecomment-163188290.

## 

-Shane

**Comment by adrianhopebailie** [comment]
> Why do you feel that the endpoint is required to be the same as the origin? I could imagine a payment app development house providing lots of different payment apps for mom and pop (e.g., smaller) retailers. Payment-Apps-R-Us would be the origin of the app and might even act as an aggregator or something, but the endpoint is www.bobs-groceries-and-gas.com/app/

To preserve SOP and security I'd recommend that when the UA does a POST to the URI that hosts the payment app it should be to the same origin that registered the app.

In this case either Payment-Apps-R-Us hosts the endpoint (most likely as they'd deal with the security aspects of doing this as well as developing the apps themselves, likely business for PSPs) or they provide the app to Bob's to both host and install.

**Comment by ianbjacobs** [comment]
@adrianhopebailie

Regarding your data example above:
- I am gathering that the "id" is private data for the payment app distributor. If that's the case, I would not suggest using a URI as the id. Also, you may want to put a comment to indicate this is private to the app distributor so that they can determine the version of app installed, or whatever.
  
  If the id is, on the other hand, intended for the mediator then I am guessing it is not necessary and the mediator will use ids that it deems necessary (or none).

**Comment by adrianhopebailie** [comment]
@ianbjacobs I don't think it's private, it is used by the publisher to probe if their app is installed later on so needs to be known to both the publisher and mediator.

Using a URL has the benefit of enabling some SOP based restrictions. e.g. If the app is installed through some side channel then the mediator is able to determine which origin is able to probe for the presence of the app.

**Comment by ianbjacobs** [comment]
@adrianhopebailie
"I don't think it's private, it is used by the publisher to probe if their app is installed later on so needs to be known to both the publisher and mediator."

It's not clear to me that the mediator needs it; they can use their own internal id when the app is registered.

"Using a URL has the benefit of enabling some SOP based restrictions. e.g. If the app is installed through some side channel then the mediator is able to determine which origin is able to probe for the presence of the app."

I would not trust the URI to determine origin; that can be faked. Instead, the system should have data from the actual origin where the information was retrieved (thus, through a protocol like HTTP).

**Comment by adrianhopebailie** [comment]
> It's not clear to me that the mediator needs it; they can use their own internal id when the app is registered.

There is nothing from stopping them doing that too. There needs to be a globally unique id for the app that is known to the publisher and the mediator. If the id is not provided by the publisher what would the publisher use to detect if their app is installed?
i.e. When calling: `navigator.payments.isPaymentAppInstalled({"https://xyzbank.com/app/"});`

> I would not trust the URI to determine origin; that can be faked. Instead, the system should have data from the actual origin where the information was retrieved (thus, through a protocol like HTTP). 

At this stage there are a number of ways proposed that an app could be registered and not all of them are done via the browser so there is no way for the mediator to associate the app with an origin other than through some property of the app (like it's ID). 

e.g. If the app is a mobile app and is installed from the mobile platform's app store how does the mediator know which origin to link the app to? There may be some mechanism to do this already, I'm not an expert when it comes to mobile apps so I don't know. I know that publishers are verified and have certificates which they use to sign their apps etc but I'm not sure if these are tied to an origin in any way.

As we are developing a Web standard, it feels correct to me to use URLs as a platform independent way to identify the same app across various deployments.

**Comment by ianbjacobs** [comment]
@adrianhopebailie 

> There needs to be a globally unique id for the app that is known to the publisher and the mediator. If 
> the id is not provided by the publisher what would the publisher use to detect if their app is installed?

I understand the publisher's need. But if it's only the publisher's need, then that data can be private to the publisher. They MIGHT use URIs but they should not be obligated to use them if the data is only for internal use.

> At this stage there are a number of ways proposed that an app could be registered and not all of them are done via the browser so there is no way for the mediator to associate the app with an origin other than through some property of the app (like it's ID). 

That's a fair point. But it is not clear to me that a URI is the way to go (since I could easily put whatever URI I want in that field). There may be multiple ways to establish the origin with confidence; on the Web it might be through HTTP. Others may wish to use PKI. If we feel origin is important, I don't think URIs as strings do the job. (There may be a way to use URIs for access to services to authenticate origin dynamically, but I'm not well-versed in that sort of thing.)

> As we are developing a Web standard, it feels correct to me to use URLs as a platform independent way to identify the same app across various deployments.

In general, I would also lean toward using URIs as identifiers, but there are other considerations (such as "short strings are easier" like we're discussing on the other thread). Here the consideration is: does a URI really tell you the origin?

**Comment by dlongley** [comment]
> As we are developing a Web standard, it feels correct to me to use URLs as a platform independent way to identify the same app across various deployments.

:+1:

**Comment by adrianhopebailie** [comment]
Renamed to use new terminology. Some useful discussion on registration is also found in #28 which has been closed to allow the discussion to continue in one place (in this thread).

**Comment by msporny** [comment]
Migrating this issue to https://github.com/w3c/browser-payment-api/issues/12
