### ISSUE TITLE
[Payment Apps] What portion of the PaymentRequest is sent to the payment app?

### ISSUE THREAD

**Issue by LaurentCastillo** [w3c/webpayments#166]
In particular, which payment methods details are forwarded to the payment app?

**Comment by webpayments** [comment]
As we discussed in London, I believe only the matching payment methods
should be forwarded.  This necessarily means that each payment method +
data needs to be signed independently so that the overall payment request
can be decomposed without compromising the integrity of some global request
signature.

On Fri, Jul 8, 2016 at 10:00 AM, Laurent Castillo notifications@github.com
wrote:

> In particular, which payment methods details are forwarded to the payment
> app?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/webpayments/issues/166, or mute the thread
> https://github.com/notifications/unsubscribe/APFrHDL4xnom4lJDNrmPa6pfzJHvWdDUks5qTmYbgaJpZM4JIHOo
> .

## 

Shane McCarron
Projects Manager, Spec-Ops

**Comment by adrianhopebailie** [comment]
Migrated https://github.com/w3c/webpayments-payment-apps-api/issues/2
