### ISSUE TITLE
Pull filters out of payment method data

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#170]
As discussed on the call, I recommend that the payment method filters be defined outside of the opaque payment method data (`data`).

``` javascript
var supportedMethods = [{
    methods: ['urn:payment-method:basic-card-payment'],
    filters: {
        networks: ['visa', 'mastercard'],
        types: ['debit']
    },
    data: {
    ...
    }
}];
```

**Comment by msporny** [comment]
+1 

I support exploring this change to the PMI spec and think that what @adrianhopebailie proposes above is a good starting point.

Things to consider:
1. Do we want to support AND/OR clauses. I'd argue that we don't because it'll make the mechanism too complicated. I expect the logic to be "for each key in the 'filters' property, at least one item in the array associated with the key has to match the payment method being filtered for the payment method to be included in the filtered set".
2. Wildcard matching and/or microsyntaxes in the filters. No, not in v1.

**Comment by adrianhopebailie** [comment]
As decided on the call on 18 August this is being closed until there are more use cases showing a need to generalize the filters
