### ISSUE TITLE
PROPOSAL: Postpone release of an HTTP API FPWD until the messaging schemas have stabilized.

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments#73]
This proposal is related to the question at #17.

Some background:
- The WG decided that we should produce an HTTP API and we are chartered to so.
- There will be benefit to aligning the messaging used in both the HTTP API and JavaScript API.
- The group's efforts are currently focused on the JavaScript API and the design of this API is likely to impact the design of any messages that are exchanged via the API.

**PROPOSAL**
The WG should wait until the JavaScript API is sufficiently mature that the messaging schemas have stabilized and then design an HTTP API based on these schemas. This would mean not publishing an FPWD of an HTTP API in March.

**Comment by msporny** [comment]
-1 for the following reasons:
1. We have enough for a rough-cut at an FPWD right now. 
2. The HTTP API is less complex than the Browser API and there aren't two proposals on the table for it, just one.
3. We should send a clear message that a browser API _and_ an HTTP API are equally important to the group.
4. Assertions made in the HTTP API may influence the Browser API. We shouldn't merely focus on the browser. There are many other types of HTTP clients out there than just browsers.

We just need a few folks to review the HTTP API and raise issues. At the very worst, we highlight those issues in the spec and push out a FPWD.

COUNTERPROPOSAL: We get 2-3 people to review the HTTP API and raise issues, include those issues in the spec, and push out a FPWD in March.

**Comment by adrianhopebailie** [comment]
@msporny the proposal is backed by two strong arguments in its favor. If you wish to :-1: the proposal can you address these too?
- There will be benefit to aligning the messaging used in both the HTTP API and JavaScript API.
- The group's efforts are currently focused on the JavaScript API and the design of this API is likely to impact the design of any messages that are exchanged via the API.

Assuming you agree with these statements then my response to the counter proposal is :-1: on the following basis:

> We have enough for a rough-cut at an FPWD right now.

What value is there in publishing a rough-cut API that has had little review from the group and is HIGHLY likely to change? I don't agree with the argument that publishing "sends a message" about the groups position on the API if the group has made a public statement that they plan to publish the API.

> The HTTP API is less contentious than the Browser API (there is no competing spec).

I don't consider the two browser API specs as "competing". They are simply collections of different ideas and approaches to solving the same problem. I expect that the final WG spec will have taken some inspiration from both even if only one is ultimately used as the starting point for a group spec.

It's quite likely that the lack of "contention" is from a lack of interest right now which is exactly the point. If we want to do this properly we should do it when the group can give it due diligence.

> We should send a clear message that a browser API and an HTTP API are equally important to the group.

Are they? You are making that assertion but I am not sure the group agrees. Certainly the lack of review time from the group dedicated to the HTTP API suggests that the browser API is the priority even if both are equally important to publish eventually.

In any case, the proposal is not to devalue or "not do" the HTTP API but to de-prioritize it to save the editors re-doing it when the messaging in the browser API stabilizes.

> Assertions made in the HTTP API may influence the Browser API. We shouldn't merely focus on the browser. There are many other types of HTTP clients out there than just browsers.

I'm not sure this is true either. It would be helpful if you could provide some examples of how this may be the case. It would appear to me that the design considerations for the browser API are far stricter and that building an HTTP API based on the same messages and flows after the fact will be trivial.

If there are user interactions that the browser API comes to depend upon that can't be done in the HTTP API then there is a necessary divergence in the designs anyway because the HTTP API is required to work without user interaction.

I am certainly NOT in favor of compromising the design of the browser API because of requirements of the HTTP API. I don't think the case for them having an identical data-model has been made. While it would be useful for developers it should not restrict the two API's from following appropriate design paths for their unique use cases and requirements.

> We just need a few folks to review the HTTP API and raise issues. At the very worst, we highlight those issues in the spec and push out a FPWD.

Why not simply publish a fresh version of this from the WPCG or WICG? What value is there in pushing this through the WG in a way that implies it's had the necessary attention from the group?

**Comment by msporny** [comment]
> If you wish to :-1: the proposal can you address these too?
> - There will be benefit to aligning the messaging used in both the HTTP API and JavaScript API.

Yes, this is true.

> - The group's efforts are currently focused on the JavaScript API and the design of this API is likely to impact the design of any messages that are exchanged via the API.

You could replace "JavaScript" with "HTTP" above and the statement would still hold. They both affect each other, and ideally we'd use the same messages in both APIs (not to mention a Bluetooth API, an NFC API, etc.)

The points above are not what I'm primarily concerned about, though, so it doesn't follow that we should de-prioritize the HTTP API just because I agree with your two points above. 

>  I don't agree with the argument that publishing "sends a message" about the groups position on the API if the group has made a public statement that they plan to publish the API.

Publishing a document as an FPWD sends a message on our priorities. It's far more powerful than just saying that the HTTP API is important to us - of course it is, but if we delay publication of an HTTP API FPWD by six months, it's clear that it's not really a priority for us. There are many things that are important to us in this group, and we'd have no problem saying that, but what we publish actually demonstrates our priorities.

**Comment by ianbjacobs** [comment]
I think the advantages of waiting to publish the HTTP API spec are:
- We seem to all agree that the JS API is primary. I believe the JS API merits our sustained focus to ensure we make progress on some core issues.
- We seem to all agree that alignment in messages is desirable (though, as I've said I don't think alignment is strictly necessary and there may be solid reasons for divergence that we may discover). We have not yet come to ground on the JS API messages. If we want alignment, it seems prudent to wait until the JS API messaging has stabilized.

Of course, I would like for us to make progress on both APIs. I am hoping that we will make enough decisions at the FTF so that the path to FPWD for the JS API is clear, and then perhaps we can devote more time to an HTTP API spec shortly thereafter.

Ian

**Comment by msporny** [comment]
> In any case, the proposal is not to devalue or "not do" the HTTP API but to de-prioritize it to save the editors re-doing it when the messaging in the browser API stabilizes.

The PaymentRequest API does not define an independent message format. Full stop.

Even if it did, you are making an assumption here that the browser API messages will stabilize before we go to FPWD. I highly doubt the browser API will stabilize in the next month or two (based on our current rate of progress). I'm happy to be proven wrong, though. :)

Waiting for the Browser API to stabilize before doing anything on the HTTP API doesn't seem like a workable strategy. Remember, an FPWD doesn't have to be anywhere close to perfect. FPWDs are published mainly to demonstrate that we are making _some_ progress and to give the world some idea of the types of things we've made it a priority to work on.

Fundamentally, if the group thinks that publishing an HTTP API is an important thing for us to do (and I think we have consensus on that), we can't push work on it out to some unknown timeframe. We should either 1) publish an FPWD of the Browser API and HTTP API at the same time, or 2) publish an FPWD of the Browser API and them immediately switch focus and publish an FPWD of the HTTP API.

The Web Payments CG's Browser API proposal demonstrates that the same messaging format can be used in multiple APIs (Browser, HTTP, Bluetooth, etc.). It demonstrates this in the spec and it demonstrates it via the web-payments.io polyfill. The Web Payments CG's Browser API _and_ the Web Payments CG's HTTP API (and ISO20022) have been designed w/ a shared message format at their core. The PaymentRequest API does not and it does not have the notion of a shared message format.

So, to go back to the proposal: Postpone release of an HTTP API FPWD until the messaging schemas have stabilized.

One of these things might be going on right now:
1. The messaging schemas are stable enough for FPWD because there is a set of specs from the Web Payments CG that demonstrates (with spec text and a polyfill) how the same messages can be used between both the Browser API and the HTTP API, or
2. We haven't had the opportunity to really dive into this in the WG, but there is nothing in the Payment Request API that enables that discussion to happen, so postponing the discussion just kicks the can down the road instead of dealing with something we really should be discussing as a group.

COUNTERPROPOSAL: Focus on releasing a Browser API FPWD by end of March 2016 and then immediately switch focus and define a common Payment Messaging Format and HTTP API  with a firm early June 2016 FPWD date (based on anything we may learn from the Browser API).

**Comment by msporny** [comment]
To be clear, one of the primary reasons I'm -1 on the original proposal, which was "Postpone release of an HTTP API FPWD until the messaging schemas have stabilized." is because we're not doing anything right now to stabilize the messaging schemas, thus pushing the HTTP API out to an unknown timeframe.

**Comment by ianbjacobs** [comment]
@msporny,

Thanks for clarifying. Your counter-proposal seems to align with my comment "I am hoping that we will make enough decisions at the FTF so that the path to FPWD for the JS API is clear, and then perhaps we can devote more time to an HTTP API spec shortly thereafter."

Indeed, I would support proposing a target date for FPWD. For example, we could aim for something like a 1 June publication, and that would give people some time to prepare additional proposals as well. To be clear: I am glad we have the CG proposal. Hearing diverse thoughts on the matter would be valuable.

Ian

**Comment by dlongley** [comment]
> Thanks for clarifying. Your counter-proposal seems to align with my comment "I am hoping that we will make enough decisions at the FTF so that the path to FPWD for the JS API is clear, and then perhaps we can devote more time to an HTTP API spec shortly thereafter."
> 
> COUNTERPROPOSAL: Focus on releasing a Browser API FPWD and then immediately switch focus and define a common Payment Messaging FPWD and HTTP API FPWD (based on anything we may learn from the Browser API).

+1 to @ianbjacobs and @msporny. Important to have a timeframe for this.

**Comment by adrianhopebailie** [comment]
This proposal was RESOLVED (more due to a lack of opposition than overwhelming support) in the 28 January meeting but was revised to include an explicit delivery date for the HTTP API.

The resolution that was passed is:

**Postpone release of an HTTP API FPWD until 1 June 2016**
