### ISSUE TITLE
How do we prevent keyboard hooking during payment?

### ISSUE THREAD

**Issue by oldoldb** [w3c/webpayments#90]
I looked through the architecture part and didn't find anything related. During payment process, when user types his login password or payment password, his environment may be insecure and some hook processes may exist, then these malicious processes can get what users type. So does our proposal contain something related with secure input? And should it be handled by which part? Payment App, Payment Method or Payment Mediator?

**Comment by adrianhopebailie** [comment]
This would happen inside the _payment app_ so the expectation is that this would be dependent on what a payment app implementation looks like in different deployment scenarios.

This threat is not unique to our architecture, it's a security consideration that apps must design for.

**Comment by oldoldb** [comment]
I see... I just wonder if our proposal can contain some mechanism related with secure input. For example, in the proposal, could we suggest Payment Mediator ( the browser) provide an element such as "secure input' (something like <input type="password" secure /> ), which can ensure that malicious processes can't hook the input.
And another question is, how does our proposal ensure that malicious scripts/attacks can't get what user types in password box?  I mean if malicious scripts is injected into current page, then what if hackers use input.value to get the password?

**Comment by ianbjacobs** [comment]
@oldoldb,

We talk a bit about security in our charter:
 https://www.w3.org/Payments/WG/charter-201510.html

In particular, we say: "There are other aspects of security (e.g., authentication of payer identity) that the Working Group will leave to individual digital payment schemes. The Working Group will not define authentication mechanisms (e.g., hardware-based solutions in securing transactions, or authenticating users via biometry or other mechanisms) but should be aware of industry developments to help ensure compatibility with the flows defined by this group."

Here is what we say about the API itself: "The design of any API should guard against the unwanted leakage of such data through exploitation of the API."

Ian

**Comment by oldoldb** [comment]
@ianbjacobs @adrianhopebailie 
Thanks for your reply! I think from what you said I have learned that these aspects of security should be considered by ISVs and this proposal will just help them with the design of the API to ensure there is no security concerns.

**Comment by rsolomakhin** [comment]
>  could we suggest Payment Mediator ( the browser) provide an element such as "secure input' (something like ), which can ensure that malicious processes can't hook the input.

We can suggest it, but browser cannot guarantee it in most cases.

Chrome can't guarantee this on the majority of platforms, because it runs as a user level process. Hooking into the keyboard requires OS level permissions. OS level processes generally have full access to user level process. User level processes cannot guard against this.

ChromeOS has slightly better guarantees for Chrome, because it [uses TPM](http://chrome.blogspot.com/2011/07/chromebook-security-browsing-more.html) and does not allow installation of any other program. Apple Pay's [Secure Element](https://support.apple.com/en-us/HT203027) may be able to provide a similar level of security.

Android is a special beast here, because users can install [custom keyboards](http://code.tutsplus.com/tutorials/create-a-custom-keyboard-on-android--cms-22615). A custom keyboard can open network connections and log everything you type, if they wanted to. So, users have to be especially careful here.

**Comment by ianbjacobs** [comment]
@rsolomakhin,

Is there something from this thread you would add to a "Security Considerations" portion of the API spec?
Ian

**Comment by rsolomakhin** [comment]
@ianbjacobs,

No, it's good, thank you.
