### ISSUE TITLE
ISO20022 terminology adoption

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments#93]
Whilst the flows have begun adopting ISO20022 terminology, the APIs, specifically the methods and field names have not been harmonised as yet

**Comment by mattsaxon** [comment]
duplicate

**Comment by fredMeignien** [comment]
Hello Matt,
I have some difficulties with the proposed terminology.
"Agent" is used in 20022 to represent the financial institution, in names as "DebtorAgent" ("Financial institution servicing an account for the debtor.") or "CreditorAgent".
So, using it to describe the Browser does not sound fitted.

"User" is too generic.
Using it to describe the "Shopper" is a bit confusing: why the Merchant or a PSP would not be "users" too ?
I agree there is a need for common vocabulary but standardizing the names is in itself a harsh task, and quite difficult to complete as long as concepts are not totally stabilized.
The big advantage of using words as "Payee" or "Payer" is that any reader can immediately understand the underlining idea. 
For example, the "Payee" may be an Administration, and not a Merchant...A reader can understand that and do on his own the adequate interpretation. If we say that the Payee is necessarily a Merchant, we introduce a restrictive connotation. That is probably why 20022 uses most of the time "Debtor" and "Creditor". But "Payer" and "Payee" are still more adequate than "Debotr" and "Creditor" because we are describing a process where the person who uses his browser to do some shopping is not a debtor until it has completed his payment ! So it is a "Shopper".

**Comment by mattsaxon** [comment]
Agent is being used in the WebPayment to mean a piece of software that acts on behalf of an Actor, so we do have a clash of terms there.

Do you have a suggested alternative from ISO20022?

**Comment by fredMeignien** [comment]
Matt,
I think we should stick to the words used up to now by Webpayment, because they are adapted to trapping the undelying logics of the API and other developments, and all the participants are now used to them.
For sure "agent" is unclear, but is there a real emergency to find a better word ? If some people find it confusing, then let's use: "piece of software" ! It is not beautiful but has the great advantage of being meaningful.
Finding the best standardization should come later, because we are not sure that new concepts are not going to show up on our way, requiring from us some semantic creativity...

**Comment by dprophet** [comment]
There is a much larger issue to address. I have documented it under

https://github.com/w3c/webpayments/issues/95

**Comment by mattsaxon** [comment]
I think we should add 'User' into the term, this would give us a DebtorUserAgent actor which maps to the term User-Agent used for browsers and the like.

**Comment by ianbjacobs** [comment]
Closing this issue as terminology harmonization happens at the payment method spec level, and there are specific repos for those specs.

**Comment by webpayments** [comment]
Je suis absent(e) du bureau jusqu'au 02/05/2018

Please kindly note my absence for the period mentioned above. You can reach
Béatrice Cocozza at +33 1 40 15 58 50


Remarque : ceci est une réponse automatique à votre message  "Re:
[w3c/webpayments] ISO20022 terminology adoption (#93)" envoyé le 25/04/2018
15:33:58.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

--------------------------------------------------------------------------------------------------------------------------------------------
Ce message et toutes les pièces jointes sont confidentiels et établis à l'intention exclusive de ses destinataires. Toute utilisation ou diffusion non autorisée est interdite. Tout message électronique est  susceptible d'altération. Le Groupement des Cartes Bancaires "CB" décline toute responsabilité au titre de ce message s'il a été altéré, déformé ou falsifié.


This message and any attachments are confidential and intended solely for the addressees. Any unauthorised use or dissemination is prohibited. E-mails are susceptible to alteration. Groupement des Cartes bancaires "CB" shall not be liable for the message if altered, changed or falsified.
